### ISSUE TITLE
Migrate github runners to newer imags

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2289] opened 2024-08-19 10:05 UTC
In nightly today [#1431](https://github.com/gardenlinux/gardenlinux/actions/runs/10448014048) I see that 

" ⚠ [nightly](https://github.com/gardenlinux/gardenlinux/actions/runs/10346682826/workflow)
This workflow ran on a hosted runner that uses the "Base Image for Ubuntu Server 22.04". This image will be deprecated in September 2024. Please setup a new runner to use the "Ubuntu 22.04 by Arm Limited" or "Ubuntu 24.04 by Arm Limited" image. This will help reduce workflow run times as there are pre-installed tools. To view the list of installed software on new images, check out https://github.com/actions/partner-runner-images repository."

Please upgrade the runners to newer supported base image before the deadline.

**Comment by fwilhe** [comment] 2024-08-19 10:23
duplicate of https://github.com/gardenlinux/gardenlinux/issues/2244

**Comment by nkraetzschmar** [comment] 2024-08-19 12:04
Runners with labels `ubuntu-latest-64core`, `ubuntu-latest-arm`, `ubuntu-latest-arm-64core` updated to ubuntu 24.04 and dropped the 16core variants as they were not used anyways.

> [!WARNING]
> This may break actions anywhere across our org if they rely on some behaviour specific to the old image. We'll need to see in the coming days what breaks

**Closed by nkraetzschmar** 2024-08-19 12:04 UTC

**Comment by fwilhe** [comment] 2024-08-19 14:14
Thanks @nkraetzschmar 

Dev workflow is green, are we aware of any other issues yet?
