### ISSUE TITLE
Some GitHub build pipelines fail at the build step with run/shm Operation not supported

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/gardenlinux#1980] opened 2024-02-27 08:38 UTC
**What happened:**
Our garden linux build pipelines fail for some build jobs with:
Error: OCI runtime error: chmod `run/shm`: Operation not supported
Looks like an issue with crun.

https://noobient.com/2023/11/15/fixing-ubuntu-containers-failing-to-start-with-systemd/ (edited) 
**Debug Logs:**
https://github.com/gardenlinux/gardenlinux/actions/runs/8055650355/job/22002987799?pr=1979#step:6:18

**Comment by Vincinator** [comment] 2024-02-27 08:51
```
NEEDRESTART-KCUR: 6.5.0-1015-azure
NEEDRESTART-KEXP: 6.5.0-1015-azure
crun version 0.17
```

**Comment by Vincinator** [comment] 2024-02-27 08:56
using the `runs-on: ubuntu-latest` in github actions will resolve to Ubuntu 22.04 (Jammy Jellyfish) 
This indeed has run 0.17 https://packages.ubuntu.com/jammy/crun

**Comment by fwilhe** [comment] 2024-02-27 09:27
The Ubuntu 22.04 image got a new version recently that bumped the kernel from 6.2.y to 6.5.y

https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240225.1

Tried to reproduce and got the older image/kernel where the build works.. don't know if this version can be selected manually.

**Comment by fwilhe** [comment] 2024-02-27 10:09
Issue: https://github.com/actions/runner-images/issues/9425

**Comment by fwilhe** [comment] 2024-02-27 16:21
Workaround is merged https://github.com/gardenlinux/gardenlinux/commit/9f6f9c53633330795bae68b3e94b1366698cfdb3

We need to revert this once the original issue is resolved, there is currently no timeline for that. Keeping this issue open to track  that.

**Comment by Vincinator** [comment] 2024-03-01 10:59
We have this issue on a boo trap stage (arm64 only) build pipeline for the PR #1962 
https://github.com/gardenlinux/gardenlinux/actions/runs/8110179750/job/22166892875?pr=1962

This PR is rebased and contains commit from #1982

**Comment by Vincinator** [comment] 2024-03-01 11:01
Workaround is for amd64 only, right? 

Looks like this setup action is skipped here https://github.com/gardenlinux/gardenlinux/actions/runs/8110179750/job/22166892875?pr=1962
 anyway 🤔

**Comment by fwilhe** [comment] 2024-03-01 11:10
> Workaround is for amd64 only, right?

yes currently amd64 is hardcoded there.

**Comment by fwilhe** [comment] 2024-05-13 07:19
This issue could be resolved by upgrading to the ubuntu 24.04 runners once they are functioning well enough. This should include a recent enough podman version. Currently it looks like the runners don't work yet.

https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md

**Comment by mxmxchere** [comment] 2024-08-01 11:05
I tried the steps to reproduce once with [`ubuntu-latest`](https://github.com/mxmxchere/gl-action/actions/runs/10196668968) and once with [`ubuntu-24.04`](https://github.com/mxmxchere/gl-action/actions/workflows/build2404.yaml).

As far as I can tell the workaround is not included (I did not include `.github/actions/setup`). Still both runs seemed to work fine. 
`ubuntu-latest` still had crun  `0.17`. `ubuntu-24.04` has crun `1.14.1`

**Comment by fwilhe** [comment] 2024-08-01 11:39
Hi @mxmxchere 

yes it seems like this issue can't be reproduced anymore. I've tried [here](https://github.com/fwilhe/jubilant-funicular/tree/main/.github/workflows).

I'm not sure why that is, but in this case it should be good to get rid of this custom crun binary, even without upgrading to ubuntu 24.04.

**Comment by mxmxchere** [comment] 2024-08-01 16:59
I think the issue has been fixed in the ubuntu jammy package of crun version `0.17+dfsg-1.1ubuntu0.1`. It seems that the bug was only present in in the version before (`0.17+dfsg-1.1`). The fixed version was released to the "update" repo 2024-04-25. 

[1] https://bugs.launchpad.net/cloud-images/+bug/2056442 (even gardenlinux is mentioned briefly)
[2] https://launchpad.net/ubuntu/+source/crun/0.17+dfsg-1.1ubuntu0.1

**Comment by mxmxchere** [comment] 2024-08-01 18:15
PR to revert the workaround: https://github.com/gardenlinux/gardenlinux/pull/2242

**Comment by mxmxchere** [comment] 2024-08-06 08:55
The reverted, merged version seems to work fine in gardenlinux/gardenlinux. I created similar PRs in [gardenlinux/repo-debian-snapshot](https://github.com/gardenlinux/repo-debian-snapshot/pull/2) and [gardenlinux/ostree-image-builder](https://github.com/gardenlinux/ostree-image-builder/pull/29). These were all the places that an orga-scoped search of `crun` found.

**Comment by mxmxchere** [comment] 2024-08-06 10:48
Ok, from my point of view we can close this issue now :)

**Comment by fwilhe** [comment] 2024-08-06 12:20
Thanks for the busywork @mxmxchere

**Closed by fwilhe** 2024-08-06 12:20 UTC
