### ISSUE TITLE
Garden Linux 658 nodes do not join Gardener Clusters anymore on GCP

### ISSUE THREAD

**Issue by marwinski** [gardenlinux/gardenlinux#585] opened 2022-01-19 08:17 UTC
**What happened**:

Garden Linux 658 nodes do not join Gardener clusters anymore on GCP

**What you expected to happen**:

Nodes should join the cluster.

**How to reproduce it (as minimally and precisely as possible)**:

Configure image and start node with this.

**Anything else we need to know**:

Reason is that apparently metadata scripts don't run:
```

Jan 19 07:59:18 shoot--dev--dm-dev-4-worker-jegi4-z1-b8c68-d9n5b systemd[572]: google-startup-scripts.service: Failed to locate executable /usr/bin/google_metadata_script_runner: No such file or directory
Jan 19 07:59:18 shoot--dev--dm-dev-4-worker-jegi4-z1-b8c68-d9n5b systemd[572]: google-startup-scripts.service: Failed at step EXEC spawning /usr/bin/google_metadata_script_runner: No such file or directory
Jan 19 07:59:18 shoot--dev--dm-dev-4-worker-jegi4-z1-b8c68-d9n5b systemd[1]: google-startup-scripts.service: Main process exited, code=exited, status=203/EXEC
Jan 19 07:59:18 shoot--dev--dm-dev-4-worker-jegi4-z1-b8c68-d9n5b systemd[1]: google-startup-scripts.service: Failed with result 'exit-code'.
```

**Environment**:

**Comment by nanory** [comment] 2022-02-03 09:59
Quick update to this issue. I talked with @waldiTM about it and there are some prerequisites before we can finish this task. These include things like:
* [x] The removal of the `google-compute-engine` package as described in #549
* [ ] Get `google-guest-agents` to `debian/testing`. It's still blocked there. We need to stay in contact with the corresponding Debian developers and check the state there.

**Comment by nanory** [comment] 2022-05-10 15:57
Another update to this issue. The `google-guest-agent` package is going to be in `testing` soon as https://tracker.debian.org/pkg/google-guest-agent stats.

Once the new version is released, the mentioned issues from above should be mitigated and be resolved.

**Comment by nanory** [comment] 2022-05-30 09:43
Hi @marwinski,

I re-tested the GCP image with the newest `google-guest-agent` version and an adjusted configuration (see #672) and it seems that the issue is gone now.

The following test result shows, that pytest was able to successfully test the GCP image on a GCP environment:
* https://github.com/gardenlinux/gardenlinux/issues/672#issuecomment-1140930265

In addition, we separately started the image on GCP and generally the image was up and running. The same applies to the corresponding systemd units:
```
systemctl status google-guest-agent.service
● google-guest-agent.service - Google Compute Engine Guest Agent
     Loaded: loaded (/lib/systemd/system/google-guest-agent.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-05-25 07:37:36 UTC; 5 days ago
   Main PID: 426 (google_guest_ag)
      Tasks: 10 (limit: 1148)
     Memory: 38.2M
     CGroup: /system.slice/google-guest-agent.service
             └─426 /usr/bin/google_guest_agent

Notice: journal has been rotated since unit was started, output may be incomplete.

systemctl status google-oslogin-cache.timer
● google-oslogin-cache.timer - NSS cache refresh timer
     Loaded: loaded (/lib/systemd/system/google-oslogin-cache.timer; enabled; vendor preset: enabled)
     Active: active (waiting) since Wed 2022-05-25 07:37:34 UTC; 5 days ago
      Until: Wed 2022-05-25 07:37:34 UTC; 5 days ago
    Trigger: Mon 2022-05-30 13:39:05 UTC; 3h 59min left
   Triggers: ● google-oslogin-cache.service

Notice: journal has been rotated since unit was started, output may be incomplete.

systemctl status google-oslogin-cache.service
○ google-oslogin-cache.service - NSS cache refresh
     Loaded: loaded (/lib/systemd/system/google-oslogin-cache.service; static)
     Active: inactive (dead) since Mon 2022-05-30 07:39:05 UTC; 2h 0min ago
TriggeredBy: ● google-oslogin-cache.timer
    Process: 147588 ExecStart=/usr/bin/google_oslogin_nss_cache (code=exited, status=0/SUCCESS)
   Main PID: 147588 (code=exited, status=0/SUCCESS)

May 30 07:39:05 localhost systemd[1]: Starting NSS cache refresh...
May 30 07:39:05 localhost google_oslogin_nss_cache[147588]: oslogin_cache_refresh[147588]: Refreshing passwd entry cache
May 30 07:39:05 localhost oslogin_cache_refresh[147588]: Refreshing passwd entry cache
May 30 07:39:05 localhost google_oslogin_nss_cache[147588]: oslogin_cache_refresh[147588]: Refreshing group entry cache
May 30 07:39:05 localhost oslogin_cache_refresh[147588]: Refreshing group entry cache
May 30 07:39:05 localhost systemd[1]: google-oslogin-cache.service: Deactivated successfully.
May 30 07:39:05 localhost systemd[1]: Finished NSS cache refresh.
```

**Comment by nanory** [comment] 2022-06-02 10:14
Hi @marwinski,

since PR #935 has been merged, this issue should be fixed now. I talked with @MrBatschner about this issue and he confirmed that we can close this issue here. If you have any questions regarding the test result, let me know.

**Closed by nanory** 2022-06-02 10:14 UTC
Labels: kind/bug
