### ISSUE TITLE
Add common static OS user 

### ISSUE THREAD

**Issue by vpnachev** [gardenlinux/gardenlinux#50] opened 2020-05-11 13:17 UTC
**What would you like to be added**:
For debugging and development purposes sometimes it is necessary to ssh on the nodes. Currently, there is no common user available to all cloud images. For example, on AWS there is the `admin` user, but on GCP it is not available. 
It would have been very nice if a common user, e.g. `gardenlinux` is available by default and can be used to ssh on the node.

**Why is this needed**:
To ease development and debugging.

**Comment by marwinski** [comment] 2020-05-12 17:14
I am quite reluctant to put this in. This opens a potential path onto the OS that we do not want. On cloud-init systems the user is always "admin". On GCP the account users together with their keys are propagated to the machines (although we probably have that disabled in Gardener). Isn't there a way to enable that though the console?

As for the "_dev" images I would not be so reluctant to do that but GCP is really the only platform where this might be useful.

**Comment by rfranzke** [comment] 2020-10-21 13:44
/touch
I agree with @vpnachev that we would want to have a static user (same name) on all infrastructures. Please make that happen.

**Comment by leonardlorenz** [comment] 2020-11-02 16:02
What user groups should this user join? Should it have a home directory? I'm guessing yes, but making sure.

**Comment by vpnachev** [comment] 2020-11-03 07:24
It would be nice to have a home directory and a group, probably the same name as the user. Also, it should be able to get sudo permissions.

**Comment by marwinski** [comment] 2020-11-09 11:30
Here is what we have discussed last Friday:

We are using the standard Debian cloud init configuration which gives us the user "admin" for all images that work with cloud init. This works well with Gardener. The problem is that GCP and Azure don't come with cloud init so the user is not created. The goal is to have this user created as well in non-cloud init environments.

**Comment by marwinski** [comment] 2020-11-11 15:00
On GCP the admin user can be provided as follows:

A ssh key can be provided in the ssh key section (not sure where precisely this is in the metadata). The format needs to be as follows:

ssh-rsa <public key> admin

The google guest-login module (https://github.com/GoogleCloudPlatform/guest-oslogin) will then create the user admin, copy the ssh key and provide sudo rights to the user.

**Comment by marwinski** [comment] 2020-11-11 15:41
@rfranzke, @vpnachev: can we close this ticket?

**Comment by marwinski** [comment] 2021-08-23 13:24
no response so I close this ticket

**Closed by marwinski** 2021-08-23 13:24 UTC
Labels: kind/enhancement, area/dev-productivity, area/ops-productivity, os/garden-linux
